<Project>

  <PropertyGroup>
    <LangVersion>Latest</LangVersion>
    <NoWarn>MSB3277</NoWarn>
    <NoPackageAnalysis>true</NoPackageAnalysis>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>

    <BaseIntermediateOutputPath>obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);obj\**</DefaultItemExcludes>
    <OutputPath>bin\$(MSBuildProjectName)\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DefineConstants>TRACE;DEBUG;JET_MODE_ASSERT</DefineConstants>
  </PropertyGroup>

  <Import Project="Plugin.props" />

  <ItemGroup>
    <Reference Include="System.Xaml" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.0" PrivateAssets="All" />
    <PackageReference Include="System.ComponentModel.Composition" Version="6.0.0" PrivateAssets="All" GeneratePathProperty="true" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="*.DotSettings" />
  </ItemGroup>

  <ItemDefinitionGroup>
    <EmbeddedResource>
      <Generator>JetResourceGenerator</Generator>
    </EmbeddedResource>
  </ItemDefinitionGroup>

  <Target Name="CopyCompositionRuntimeAssembly" AfterTargets="Build" Condition="Exists('$(PkgSystem_ComponentModel_Composition)\lib\netstandard2.0\System.ComponentModel.Composition.dll')">
    <Copy
      SourceFiles="$(PkgSystem_ComponentModel_Composition)\lib\netstandard2.0\System.ComponentModel.Composition.dll"
      DestinationFolder="$(OutputPath)"
      SkipUnchangedFiles="true" />
  </Target>

</Project>
