// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MFractor.VS.Windows
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidMFractorPackageString = "9772085d-2cd1-46f3-aa46-c62ee90fefec";
        public static Guid guidMFractorPackage = new Guid(guidMFractorPackageString);

        public const string guidMFractorTopMenuCmdSetString = "9cff72df-e0c4-4ced-befe-0f415ae7cb6f";
        public static Guid guidMFractorTopMenuCmdSet = new Guid(guidMFractorTopMenuCmdSetString);

        public const string guidMFractorSolutionCmdSetString = "9cca1067-4323-4f66-b269-5ae6bdd8141b";
        public static Guid guidMFractorSolutionCmdSet = new Guid(guidMFractorSolutionCmdSetString);

        public const string guidMFractorNavigationCmdSetString = "ef1e3db8-d10b-4bb5-b254-68b76936e492";
        public static Guid guidMFractorNavigationCmdSet = new Guid(guidMFractorNavigationCmdSetString);

        public const string guidImagesString = "7df7500b-37a0-4d31-b9fd-f27538f26bae";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidIconSettingsString = "e7821d74-761f-4061-8d5a-e1c63edc6569";
        public static Guid guidIconSettings = new Guid(guidIconSettingsString);

        public const string guidIconLicenseString = "2ee20b56-a0a1-46e2-b17e-1dbb3a8d4a36";
        public static Guid guidIconLicense = new Guid(guidIconLicenseString);

        public const string guidIconCleanString = "b5a2b110-2222-45f3-9ad3-dbb897bb5aef";
        public static Guid guidIconClean = new Guid(guidIconCleanString);

        public const string guidIconCompressString = "3679d4ce-06b8-44a6-bf2d-79c368fb39f3";
        public static Guid guidIconCompress = new Guid(guidIconCompressString);

        public const string guidIconImportImageString = "c6c6c019-28bf-49d7-831b-fbf61002abe1";
        public static Guid guidIconImportImage = new Guid(guidIconImportImageString);

        public const string guidIconImportFontString = "5037d665-c33a-46a3-ac6f-cc9cb6239c87";
        public static Guid guidIconImportFont = new Guid(guidIconImportFontString);

        public const string guidIconImportAppIconString = "6f9adf98-1877-42ab-881f-5e5c690fda43";
        public static Guid guidIconImportAppIcon = new Guid(guidIconImportAppIconString);

        public const string guidIconManageImageAssetsString = "55acbd6c-e13d-4bb4-b285-6a18c41a423f";
        public static Guid guidIconManageImageAssets = new Guid(guidIconManageImageAssetsString);

        public const string guidIconSynchronizeString = "3776aa89-affa-4bd2-ab22-773130d6ad29";
        public static Guid guidIconSynchronize = new Guid(guidIconSynchronizeString);

        public const string guidIconBookString = "bba8e78b-0e5e-425f-ac50-8b22dd2812b8";
        public static Guid guidIconBook = new Guid(guidIconBookString);

        public const string guidIconEmailString = "baabfbae-003e-4447-ba9e-046ea88c698a";
        public static Guid guidIconEmail = new Guid(guidIconEmailString);

        public const string guidIconFeedbackString = "51666105-6898-4ba9-b1bf-42bc1e725bfc";
        public static Guid guidIconFeedback = new Guid(guidIconFeedbackString);

        public const string guidIconGitterString = "f647eaf0-9d4b-4273-b4c7-5e3e9a6ed99d";
        public static Guid guidIconGitter = new Guid(guidIconGitterString);

        public const string guidIconSlackString = "43506343-3cef-4c04-8026-a8993626c937";
        public static Guid guidIconSlack = new Guid(guidIconSlackString);

        public const string guidIconTwitterString = "2fdbcd5f-d0b4-4c3e-8d58-daeeee08c8f5";
        public static Guid guidIconTwitter = new Guid(guidIconTwitterString);

        public const string guidIconCodeBehindString = "01d69358-d6dd-4341-a5ee-8c29eaaea562";
        public static Guid guidIconCodeBehind = new Guid(guidIconCodeBehindString);

        public const string guidIconViewModelString = "ac81709a-9cd3-4546-9b09-33422e0621a6";
        public static Guid guidIconViewModel = new Guid(guidIconViewModelString);

        public const string guidIconXamlString = "359f54ce-843c-43a8-b626-4bda3489df32";
        public static Guid guidIconXaml = new Guid(guidIconXamlString);

        public const string guidIconMvvmString = "03d723a8-6a2c-419f-95a8-df99025f563a";
        public static Guid guidIconMvvm = new Guid(guidIconMvvmString);

        public const string guidIconLocalizationString = "108744a8-2655-40b7-bc82-f6f604248534";
        public static Guid guidIconLocalization = new Guid(guidIconLocalizationString);

        public const string guidIconValueConverterString = "36dac197-0e4b-4c47-b245-c02ca57f1ffb";
        public static Guid guidIconValueConverter = new Guid(guidIconValueConverterString);

        public const string guidXamlCmdSetString = "4c87b692-1202-46aa-b64c-ef01faec53da";
        public static Guid guidXamlCmdSet = new Guid(guidXamlCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MFractor_Menus_MainMenu = 0x1000;
        public const int MFractor_Menus_About = 0x1010;
        public const int MFractor_Menus_Support = 0x1011;
        public const int MFractor_Menus_Wizards = 0x1012;
        public const int MFractor_Menus_Import = 0x1013;
        public const int MFractor_Menus_Actions = 0x1014;
        public const int MFractor_Menus_Legal = 0x1015;
        public const int MFractor_Groups_MainMenu = 0x2001;
        public const int MFractor_Groups_MainMenu_Segment1 = 0x2003;
        public const int MFractor_Groups_MainMenu_Segment2 = 0x2004;
        public const int MFractor_Groups_MainMenu_Segment3 = 0x2005;
        public const int MFractor_Groups_Menus_Wizards = 0x2006;
        public const int MFractor_Groups_Menus_Import = 0x2007;
        public const int MFractor_Groups_Menus_Actions = 0x2008;
        public const int MFractor_Groups_Menus_About = 0x2009;
        public const int MFractor_Groups_Menus_Support = 0x2010;
        public const int MFractor_Groups_SolutionExplorer_Import = 0x2011;
        public const int MFractor_Groups_Menus_Legal = 0x2012;
        public const int MFractor_Commands_LicenseInfo = 0x1100;
        public const int MFractor_Commands_Buy = 0x1101;
        public const int MFractor_Commands_Preferences = 0x1102;
        public const int MFractor_Commands_ManageImageAssets = 0x1103;
        public const int MFractor_Commands_Wizards_LocalizeDocument = 0x1112;
        public const int MFractor_Commands_Wizards_Mvvm = 0x1104;
        public const int MFractor_Commands_Wizards_ValueConverter = 0x1105;
        public const int MFractor_Commands_ImportFont = 0x1106;
        public const int MFractor_Commands_ImportImageAsset = 0x1107;
        public const int MFractor_Commands_ImportIconWizard = 0x1119;
        public const int MFractor_Commands_ResyncMFractor = 0x1108;
        public const int MFractor_Commands_Activate = 0x1109;
        public const int MFractor_Commands_About = 0x1110;
        public const int MFractor_Commands_ThirdParty = 0x1111;
        public const int MFractor_Commands_PrivacyPolicy = 0x1113;
        public const int MFractor_Commands_EndUserLicense = 0x1114;
        public const int MFractor_Commands_RecoverLicense = 0x1115;
        public const int MFractor_Commands_LicenseSummary = 0x1116;
        public const int MFractor_Commands_Onboarding = 0x1118;
        public const int MFractor_Commands_Support_Slack = 0x1501;
        public const int MFractor_Commands_Support_Gitter = 0x1502;
        public const int MFractor_Commands_Support_Twitter = 0x1503;
        public const int MFractor_Commands_Support_Email = 0x1504;
        public const int MFractor_Commands_Support_SubmitFeedback = 0x1505;
        public const int MFractor_Commands_Support_Documentation = 0x1506;
        public const int MFractor_Commands_Debug_Lab = 0x1600;
        public const int MFractor_Commands_ImportFont_SolutionExplorer = 0x1701;
        public const int MFractor_Commands_ImportImageAsset_SolutionExplorer = 0x1702;
        public const int MFractor_Commands_ImportIconWizard_SolutionExplorer = 0x1703;
        public const int MFractor_Groups_Solution = 0x0001;
        public const int MFractor_Commands_Solution_DeleteOutputFolders = 0x1001;
        public const int MFractor_Commands_Solution_CleanAndCompress = 0x1002;
        public const int MFractor_Commands_Solution_DeleteImageAsset = 0x1003;
        public const int MFractor_Commands_Solution_GenerateFontGlyphCodeClass = 0x1042;
        public const int MFractor_Commands_Solution_ManageImageAssets = 0x1004;
        public const int MFractor_Commands_Solution_CreateClassFromClipboard = 0x1005;
        public const int MFractor_Commands_Solution_Scaffold = 0x1006;
        public const int MFractor_Commands_Solution_CopyAndroidPackageId = 0x1007;
        public const int MFractor_Commands_Solution_CopyiOSBundleId = 0x1008;
        public const int MFractor_Commands_Solution_AddExportFontDeclaration = 0x1009;
        public const int MFractor_Commands_Solution_OpenAndroidManifest = 0x1010;
        public const int MFractor_Commands_Solution_ConvertToCSharp9 = 0x1801;
        public const int MFractor_Groups_Navigation = 0x0001;
        public const int MFractor_Groups_Navigation_SolutionPad = 0x0002;
        public const int MFractor_Commands_Navigation_GoToRelationalImplementation = 0x1001;
        public const int MFractor_Commands_Navigation_GoToRelationalDefinitionCodeBehind = 0x1002;
        public const int MFractor_Commands_Navigation_GoToRelationalDefinition = 0x1003;
        public const int MFractor_Commands_Navigation_GoToXamlSymbol = 0x1004;
        public const int MFractor_Commands_Navigation_FindCustomRenderers = 0x1005;
        public const int MFractor_Logo = 0x0001;
        public const int IconSettings = 0x0001;
        public const int IconLicense = 0x0001;
        public const int IconClean = 0x0001;
        public const int IconCompress = 0x0001;
        public const int IconImportImage = 0x0001;
        public const int IconImportFont = 0x0001;
        public const int IconImportAppIcon = 0x0001;
        public const int IconManageImageAssets = 0x0001;
        public const int IconSynchronize = 0x0001;
        public const int IconBook = 0x0001;
        public const int IconEmail = 0x0001;
        public const int IconFeedback = 0x0001;
        public const int IconGitter = 0x0001;
        public const int IconSlack = 0x0001;
        public const int IconTwitter = 0x0001;
        public const int IconCodeBehind = 0x0001;
        public const int IconViewModel = 0x0001;
        public const int IconXaml = 0x0001;
        public const int IconMvvm = 0x0001;
        public const int IconLocalization = 0x0001;
        public const int IconValueConverter = 0x0001;
        public const int editorContextMenu = 0x0103;
    }
}