// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MFractor.VS.Windows
{
    internal sealed partial class Vsix
    {
        public const string Id = "MFractor.VSWindows.9e8ace0e-61dd-486f-bfeb-0c7ad1fc0b1c";
        public const string Name = "MFractor";
        public const string Description = @"A powerful productivity tool for Xamarin developers.";
        public const string Language = "en-US";
        public const string Version = "4.4.10";
        public const string Author = "Matthew Robbins";
        public const string Tags = "xamarin;xamarin.forms;android;ios;XAML;C#;.NET";
    }
}
