using System;
using MFractor.Work;
using Microsoft.CodeAnalysis;

namespace MFractor.Ide.WorkUnits
{
    /// <summary>
    /// An <see cref="IWorkUnit"/> that performs the IDE's go to symbol behaviour.
    /// </summary>
    public class NavigateToSymbolWorkUnit : WorkUnit
    {
        public ISymbol Symbol { get; }

        public bool IncludeAutoGeneratedSymbols { get; }

        public bool AllowMultipleSymbolResolve { get; }

        public bool HighlightSymbolIfDocumentAlreadyOpen { get; set; } = true;

        public NavigateToSymbolWorkUnit(ISymbol symbol,
                                        bool includeAutoGeneratedSymbols,
                                        bool allowMultipleSymbolResolve = true)
        {
            Symbol = symbol;
            IncludeAutoGeneratedSymbols = includeAutoGeneratedSymbols;
            AllowMultipleSymbolResolve = allowMultipleSymbolResolve;
        }
    }
}
